# Generated by Django 4.2.5 on 2024-03-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guerrero',
            name='cooldown',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='guerrero',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='guerrero',
            name='imagen',
            field=models.ImageField(upload_to='myapp/static/guerreros/'),
        ),
        migrations.AlterField(
            model_name='guerrero',
            name='sonido',
            field=models.FileField(upload_to='myapp/static/sonidos/'),
        ),
    ]
