# Generated by Django 4.2.5 on 2024-03-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_historialgold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guerrero',
            name='sonido',
            field=models.FileField(upload_to=''),
        ),
    ]
