# Generated by Django 4.2.5 on 2024-03-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cooldown_actual',
            field=models.IntegerField(default=0),
        ),
    ]
