# Generated by Django 4.2.5 on 2024-03-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_compra_cooldown_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='habilitado_farmear',
            field=models.BooleanField(default=True),
        ),
    ]
