# Generated by Django 4.2.5 on 2024-03-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_guerrero_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='hora_habilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
