# Generated by Django 4.2.5 on 2024-03-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_life_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='life',
            name='value',
            field=models.IntegerField(),
        ),
    ]
