# Generated by Django 4.2.5 on 2024-03-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_life_last_updated_alter_life_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guerrero',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='life',
            name='value',
            field=models.IntegerField(default=50),
        ),
    ]
