# Generated by Django 4.2.5 on 2024-03-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_guerrero_imagen_alter_life_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('observacion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=1)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tower_images/')),
            ],
        ),
    ]
