# Generated by Django 4.2.5 on 2024-03-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_tower_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='efecto',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
