# Generated by Django 4.2.5 on 2024-03-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_tower_efecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guerrero',
            name='rareza',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], max_length=20),
        ),
    ]
