# Generated by Django 4.2.5 on 2024-03-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_registrocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocompra',
            name='habilitado_farmear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='hora_habilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='cooldown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tower',
            name='produccion',
            field=models.IntegerField(default=0),
        ),
    ]
