# Generated by Django 4.2.5 on 2024-03-29 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_produccion_tower_produccion_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='date',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='hour',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='fecha_retiro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
