# Generated by Django 4.2.5 on 2024-03-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_compracofre'),
    ]

    operations = [
        migrations.AddField(
            model_name='guerrero',
            name='tipo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
