# Generated by Django 4.2.5 on 2024-04-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_guerrero_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='tower_A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='tower_B',
            field=models.BooleanField(default=False),
        ),
    ]
