# Generated by Django 4.2.5 on 2024-04-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_withdraw_tower_a_withdraw_tower_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='guerrero',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
