# Generated by Django 4.2.5 on 2024-04-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_guerrero_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='life',
            field=models.IntegerField(default=0),
        ),
    ]
